name: "ğŸ”– Sync GitHub Labels"

on:
  push:
    branches:
      - main # main ë¸Œëœì¹˜ì— pushí•  ë•Œ ì‹¤í–‰

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 'github_token'ì´ ì•„ë‹ˆë¼ 'token' ì‚¬ìš©
          manifest: ".github/labels.yml"
          prune: true # ê¸°ì¡´ ë¼ë²¨ì„ ì‚­ì œí•˜ì§€ ì•Šë„ë¡ ì„¤ì • (ì›í•˜ëŠ” ê²½ìš° trueë¡œ ë³€ê²½ ê°€ëŠ¥)
